# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
parameters:
- name: myParam
  type: string
  default: "defaultValue"

trigger:
- master

pr:
- master

strategy:
  matrix:
    dotnet6_linux:
      imageName: "ubuntu-latest"
      dotnetVersion: "6.0.x"
  maxParallel: 1
  
pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '$(dotnetVersion)'

- script: Write-Output "Parameter value is ${{ parameters.myParam }}"

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
